[build]
rustflags = ["--cfg", "tokio_unstable"]

[profile.dev]
opt-level = 0

[profile.release-max]
inherits = "release"
rustflags = ["-C", "target-cpu=native", "-Z", "tune-cpu=native"]
codegen-units = 1
lto = "fat"
panic = "abort"
incremental = false
